name: Test Execution and Report Publishing

on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'Tags JUnit para executar'
        required: false
        default: ''

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run tests with Maven
        run: |
          mvn test -Dgroups="${{ inputs.tags }}"

      - name: Generate test report
        run: |
          # Converte relatório JUnit para formato amigável
          npm install jest jest-junit
          npx jest-junit --reporters=default --reporters=jest-junit

      - name: Publish report
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: reports/

  publish-dashboard:
    needs: run-tests
    runs-on: ubuntu-latest
    steps:
      - name: Download test results
        uses: actions/download-artifact@v3
        with:
          name: test-results

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dashboard
          keep_files: true
